name: GitHub Pages

on:
  push:
    tags:
      - release/current
    paths:
      - .github/workflows/gh-pages.yml
      - src/docs
      - self-check
      - docToolchainConfig.groovy
      - dtcw
      - dtcw.bat
      - generate-pages
  workflow_dispatch: {}

jobs:
  pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
    env:
      DTC_HEADLESS: true
    steps:
      - name: Install dot (Graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}"
          restore-keys: ${{ runner.os }}-gradle

      - name: Cache .doctoolchain
        uses: actions/cache@v2
        with:
          path: ~/.doctoolchain
          key: "${{ runner.os }}-doctoolchain-${{ hashFiles('**/lockfiles') }}"
          restore-keys: ${{ runner.os }}-doctoolchain

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          # SonarQube requires JDK 17 or higher
          java-version: 17

      - name: Check out
        uses: actions/checkout@v2

      - name: Generate Pages
        run: ./generate-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/tags/release/current' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

