name: Run Gradle
on:
  pull_request:
  push:
  workflow_dispatch: {}
jobs:
  gradle:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew check --scan -stacktrace