name: Gradle Build Check
on:
  pull_request:
  push:
  workflow_dispatch: {}
jobs:
  gradle:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Execute Gradle build
        run: ./gradlew clean check integrationTest --scan -stacktrace

      - name: 'Publish Test Results'
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            **/build/test-results/**/*.xml

      - name: JaCoCo Test Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: "htmlSanityCheck-gradle-plugin/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml"
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
